// <auto-generated />
namespace ZinciriKirma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v_17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_17));
        
        string IMigrationMetadata.Id
        {
            get { return "201905280553525_v_17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
